require('config')
require('options')
require('ai')
require('lsp')
require('flutter')
require('ui')
require('editor')
require('competitive')
require('keybindings')
require('lilyponds')
if vim.g.neovide then require('neovide') end
require('autocmds')
