local reloadFeature = require("features.reload")
local windowFeature = require("features.window")
local splitViewFeature = require("features.split_view")
local appLauncherFeature = require("features.app_launcher")
local arrowRemapFeature = require("features.arrow_remap")
local shutdownFeature = require("features.shutdown")
local commandsFeature = require("features.commands")
local appBindingsFeature = require("features.app_bindings")

local appsConfig = require("config.apps")
local arrowsConfig = require("config.arrows")
local splitViewConfig = require("config.split_view")
local appBindingsConfig = require("config.app_bindings")

reloadFeature.setup()
windowFeature.setup()
splitViewFeature.setup(splitViewConfig)
appLauncherFeature.setup(appsConfig)

local arrowCleanup = arrowRemapFeature.setup(arrowsConfig)
commandsFeature.setup({}, { commanding = require("commanding") })
appBindingsFeature.setup(appBindingsConfig, { utils = require("utils") })
shutdownFeature.setup({ arrowCleanup })
